name: CIW

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set credentials
      env:
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
      run: |
        echo Setting credentials...
        git config --global hub.protocol https
        git config --global user.email "luistupa7@gmail.com"
        git config --global user.name "Luis Tupa"
        git remote set-url origin https://$USER_NAME:$USER_PASSWORD@github.com/ltsfran/ltsfran.github.io.git
    - name: Install dependencies
      run: |
        echo Installing dependencies...
        cd ./app
        npm install
    - name: Build statics and deploy to GH Pages
      run: |
        echo Deploying...
        cd ./app
        npm run deploy