name: CIW

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Deploy Static Files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x.0]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: |
        cd ./app
        yarn install --production
    - name: Build static files
      run: |
        cd ./app
        yarn build
        touch ./dist/.nojekyll
    - name: Deploy to GH Pages
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        BRANCH: gh-pages
        FOLDER: app/dist
